- id: set_var_defaults
  name: Reset game variable values
  description: Sets the current value of .asset files that inherit GameVariable to their default values.
  entry: set-var-defaults
  language: python
  stages: [pre-commit, manual]
